### PR TITLE
User profile page (+ officer info input)

### PR DESCRIPTION
**Pull request by EarthenSky**
Close https://github.com/CSSS/csss-site-frontend/issues/8 and https://github.com/CSSS/csss-site-backend/issues/76 (i suppose)

This PR adds the `/profile` page, which, when a user has been selected as an officer, stores officer information that needs to be input.

### CODE REVIEW

**Comment by EarthenSky** [comment]
https://github.com/user-attachments/assets/f35517db-971c-4802-85a6-05c882cfbb3c

**Comment by EarthenSky** [comment]
Screenshot 2024-08-24 003235

**Review by micahdbak — APPROVED** [review]
I love

Is it ready

I approve

Merge when u want 

HECK YES

**Comment by micahdbak** [comment]
Looks like this PR already uses /api, so that's good! Triple check for me tho, pls

**Comment by micahdbak** [comment]
@EarthenSky - just merged main - please pull and confirm everything works with your backend - then merge pls

**Comment by EarthenSky** [comment]
Screenshot 2024-09-01 171826

Officer info is complete. 

TODOs
- [ ] add an input for officer term data, and stop users from modifying term data that's not current

**Comment by EarthenSky** [comment]
This PR is getting big (like https://github.com/CSSS/csss-site-backend/pull/70), so I'll finish the interface for officer term in a separate PR (issue https://github.com/CSSS/csss-site-backend/issues/84).

**Pull request merged**
