### PR TITLE
fall hacks -> frosh

### PR DESCRIPTION
**Pull request by EarthenSky**

### CODE REVIEW

**Comment by micahdbak** [comment]
Oop, good catch 😭

**Comment by micahdbak** [comment]
TY for making the patch, mark as ready for review when ur done 🙏

**Comment by EarthenSky** [comment]
Screenshot 2024-09-05 135237

**Comment by micahdbak** [comment]
omfg thank u for making the rooms clickable, i couldnt figure out how to do it via URL; will remember here on out!!!

**Review by micahdbak — APPROVED** [review]

**Pull request merged**
